Lucas_first_patch
aarnphm/tinymorph pull request #83
Opened 2024-10-07 20:02 UTC by lucas-lizhiwei

first patch

2024-10-07 20:18 UTC, lucas-lizhiwei commented
I'm uploading this first patch, I'll make it align with the Resonale format in next patch, with following three parts

2024-10-07 21:10 UTC, aarnphm requested changes
Hi there, let's not garbled with AI-generated content

2024-10-08 00:39 UTC, lucas-lizhiwei commented
Hi! Yes, I'm doing the rewrite. Do you think the key points(for each section before the ":" ) can be valuable to keep or do you recommend me to start them all over again as well?

2024-10-08 02:56 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +- **Backward Compatibility**: User's personalised preferences and setups should be kept and compatible with the new updates and maintenance.
also no need to mention backward compat for now.

2024-10-11 19:28 UTC, lucas-lizhiwei reviewed
Okay

2024-10-11 19:30 UTC, lucas-lizhiwei reviewed
Please review

2024-10-11 20:18 UTC, aarnphm approved these changes

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: The manual and technical document should be accessed by user without any barrier. Accompanied with the software, corresponding updates should also implemented on documents.
```suggestion
> [!IMPORTANT] OER-PR2
>
> Relevant documentation should be accessible by users.

Rationale: Usage manuals and technical-related details should be easily accessible from `tinymorph`'s interface.

> [!IMPORTANT] OER-PR3
>
> Feedback should also be included within the interface

Rationale: Enable user-feedback to improve the product.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: There should be a platform or document used to demonstrate the relevant version information and new release updates, like bug fixes and improvements.
```suggestion
> [!IMPORTANT] OER-RR1
>
> Release cycle must utilize current GitHub CD workflow.

Rationale: Version control and release cycle should follow semantic versioning and utilize GitHub's CI for automation.

> [!IMPORTANT] OER-RR2
>
> End-to-end tests should pass before deploying to production.

Rationale: end-to-end workflow must be the minimum for all feature development to ensure `tinymorph` is functional within a production environment.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Regular updates, including adding features and addressing bugs on user end, and iteration on model should be carried out during the tinymorph's life span as maintenance.
```suggestion
> [!IMPORTANT] OER-MR1
>
> Security updates must be done periodically

Rationale: Regular security updates to adjacent dependencies must be done quickly to avoid certain CVE exploits if they exist.

> [!IMPORTANT] OER-MR2
>
> Feature integrations must pass existing tests

Rationale: Given features works must not fail existing testing infrastructure.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: There should be a platform used to gather and record the feedback or report for bugs from end user as supplement for future development.
```suggestion
> [!IMPORTANT] OER-SR1
>
> User feedback loop must be present.

Rationale: For further development and UX improvement, a user-feedback loop is required. 
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Tinymorph should be able to provide services over the common OS including macOS, Windows and linux, and user end should perform well on average hardware environment.
```suggestion
> [!IMPORTANT] OER-AR1
>
> `tinymorph` must be able to run with existing users' environment

Rationale: For web interface, `tinymorph` should be able to run on all existing modern browser. For packaged binary, it must support major architectures and operating system. 
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: In the first edition of tinymorph development, it only support for English input content and can only generate text in English.
```suggestion
> English supports

Rationale: English will be supported for alpha release of `tinymorph`. This is due to the limited capabilities of models when dealing with multilingual inputs.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: If there are any inappropriate content specific to the culture of generated output language, they should be filtered out.
```suggestion
> Cultural reference must be factual

Rationale: If given cultural references are generated, it must utilize tools to fact-check given suggestions (using web-search).
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Currently only LTR habit implemented in the tinymorph to present output.
```suggestion
> [!IMPORTANT] CulR-CR3
>
> Support left-to-right (LTR) reading flow

Rationale: Panels will be presented in LTR manner. RTL will be supported once multilingual are added. 
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Since the genereted content invloves Open-AI model output, the generated content is subject to OpenAI's license and terms of use, which is not protectable under US copyright law
```suggestion
> Suggestion must follow strict US copyright law.

Rationale: Certain suggestions, if any, uses additional contents, references must be made to ensure copyright law compliance.

> [!IMPORTANT] CompR-LR2
>
> [SOC2](https://www.vanta.com/products/soc-2) compliance

Rationale: `tinymorph` should follow SOC-2 attestation for its inference server.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: To use the language model in host server, user need to send necessary information based on input text to trigger language model. Users are consent for this data collection.
```suggestion
> Users permission to run inference against their content

Rationale: `tinymorph` will require users' inputs to make corresponding suggestions. In other words, existing user content will be sent during inference requests.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Tinymorph adhere to Hypertext Transfer Protocol (HTTP/1.1 and HTTP/2) standards as defined by the Internet Engineering Task Force (IETF) in RFC 2616 (for HTTP/1.1) and RFC 7540 (for HTTP/2
```suggestion
> follows standard HTTP protocol for client-server communication

Rationale: `tinymorph` will adhere to Hypertext Transfer Protocol (HTTP/1.1) standards as defined by the Internet Engineering Task Force (IETF) in RFC 2616 (for HTTP/1.1).
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Whenever there is a iteration on the model running on host server, it should make no effect to end user's generating process. An updating strategy that change the model when no user is in
```suggestion
> Minimal downtime during migration process

Rationale: When the inference server is updating or maintaining, users should be aware of the downtime, given it shouldn't affect users' workflow.
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: If there is a new edition of UI is distributed, a notice on current UI should be provided for user to access to latest edition.
```suggestion
```

2024-10-11 20:18 UTC, aarnphm commented on docs/content/SRS/SRS.md
> +Rationale: Whenever there is a iteration on the user end interface, tinymorph need to make local stored user preferences readable and in up-to-date format.
```suggestion
> [!IMPORTANT] MNP-DMTNS1
>
> Migration in future config format should ensure backward compatibility for one-time transition

Rationale: When configuration or certain features require breaking change, `tinymorph` must be able to migrate existing configuration to the new format without breaking change. 
```

2024-10-11 20:21 UTC, aarnphm approved these changes

2024-10-11 20:22 UTC, merged